### ISSUE TITLE
https://github.com/linuxxx/EasyPR  运行出错ndk问题

### ISSUE THREAD

**Issue by zwyzzz888** [lucher/EasyPR_Android_RN#1]
windows平台   修改为  commandLine "$ndkDir/ndk-build.cmd"之后
报
E:\android\android-ndk-r9d\platforms\android-18\arch-arm\usr\include\limits.h
Error:(89, 27) sys/syslimits.h: No such file or directory    
这个错误   
问下项目环境ndk用的是什么版本啊?  
能提供下联系方式么? 咨询点问题

**Comment by lucher** [comment]
app/build.gradle里有ndk版本：
commandLine "/home/lucher/main/softs/ndk/android-ndk-r14b/ndk-build"

**Comment by zwyzzz888** [comment]
后来看到了  这里的配置路径没有使用$ndk
后来手动改成自己的路径了 我的是r10e 也运行成功了
改过照相的感觉识别速度比原来的变慢了  可能是图片处理慢了?  还没看代码
