### ISSUE TITLE
some problem occured for Android 

### ISSUE THREAD

**Issue by wolfjobs** [lucher/EasyPR_Android_RN#2]
I fellow ur step of ur blog, changed the path of NDK,but when I run this project with "react-native run-android",it show me that ：

**`* What went wrong:
Execution failed for task ':app:buildNative'.
> A problem occurred starting process 'command '/Users/fengjun/Library/Android/sdk/ndk-bundle''
`**

**Comment by lucher** [comment]
@wolfjobs I'm not sure what exactly problem this is, but it looks like there is something wrong with ur ndk, Please make sure it works well.
